### ISSUE TITLE
pop save filters window very time

### ISSUE THREAD

**Issue by daoweil** [TextAnalysisTool/Releases#39]
if we choose filters, but did not change them at all, very time when try to close the APP, it pops window about save fiters, it's very painful that if we have open lots instance, we need to click 'NO' one by one when we want to close all the instances by one click :), can we change it to be more friendly?

**Comment by vincec-msft** [comment]
Hi daoweil,

Could you give a little more detail about the issue? I'm trying to understand more because I don't see the prompts you mentioned.

What do you mean by "choose filters, but did not change them?" How were they chosen? Were they loaded from a file?

When you say "we need to click 'NO' one by one" do you mean that you are closing multiple copies of the app at once by right clicking on the taskbar icon and selecting "Close all windows?" Does the prompt to save happen if you're closing just one instance of the app with File/Exit or clicking the close icon in the upper right of the title bar?

Thanks!

**Comment by daoweil** [comment]
thanks for attention.


what I meant is, when I just select some pre-stored filters, and close the tool, it alway show the confirm windows like below. if I open lots of txts by tool, and close all tabs, many confirm windows like this will come out, and I need do it one by one. can we add some options to disable 'ask save when close' ?

[cid:019c71fc-8a9c-4e53-83e6-dc36e573b143]

[cid:776f5a1c-ef51-4d35-a788-bef7dbaa5259]

________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2016年11月11日 1:41
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Hi daoweil,

Could you give a little more detail about the issue? I'm trying to understand more because I don't see the prompts you mentioned.

What do you mean by "choose filters, but did not change them?" How were they chosen? Were they loaded from a file?

When you say "we need to click 'NO' one by one" do you mean that you are closing multiple copies of the app at once by right clicking on the taskbar icon and selecting "Close all windows?" Does the prompt to save happen if you're closing just one instance of the app with File/Exit or clicking the close icon in the upper right of the title bar?

Thanks!

―

**Comment by vincec-msft** [comment]
Here's what I tried:

1) Launch TextAnalysisTool.NET (version 2016-06-16)
2) File / Load Filters...
3) Pick a .tat file to load
4) Close the app (X button in the title bar, or Alt+F4)

I didn't see a prompt to save the filters.

I also tried File / Recent Filter Files to load the .tat file and also did not see the prompt.

If you make any changes to the filters, even enabling or disabling them, then you will be prompted to save. That's intentional. But if there have been no changes then I need more details in order to reproduce the issue. How are your steps different than mine above?

**Comment by daoweil** [comment]
thanks for prompt reply.


yes, can we add a option in configuration that when enableing/disabling them, don't ask for save? [😊]

________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2016年11月11日 3:07
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Here's what I tried:

1) Launch TextAnalysisTool.NET (version 2016-06-16)
2) File / Load Filters...
3) Pick a .tat file to load
4) Close the app (X button in the title bar, or Alt+F4)

I didn't see a prompt to save the filters.

I also tried File / Recent Filter Files to load the .tat file and also did not see the prompt.

If you make any changes to the filters, even enabling or disabling them, then you will be prompted to save. That's intentional. But if there have been no changes then I need more details in order to reproduce the issue. How are your steps different than mine above?

**Comment by vincec-msft** [comment]
What are you saying yes to?

We can consider an option but I'm still trying to understand why you're getting prompted.

**Comment by daoweil** [comment]
'if you make any changes to the filters, even enabling or disabling them, then you will be prompted to save. That's intentional.'

________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2016年11月11日 3:33
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


What are you saying yes to?

We can consider an option but I'm still trying to understand why you're getting prompted.

―

**Comment by DavidAnson** [comment]
If I'm reading this right, the request would be to add an option like "Prompt to save filter when rules have been enabled/disabled" which defaults to true (current behavior). If false, filters would only be considered "dirty" if rules had been added, removed, or edited.

**Comment by daoweil** [comment]
That is correct

On Nov 11, 2016 12:16 PM, David Anson <notifications@github.com> wrote:

If I'm reading this right, the request would be to add an option like "Prompt to save filter when rules have been enabled/disabled" which defaults to true (current behavior). If false, filters would only be considered "dirty" if rules had been added, removed, or edited.

**Comment by DavidAnson** [comment]
Fixed in the 2016-12-09 release, thank you!

**Comment by daoweil** [comment]
Hi,


I try to mask some filters to dirty, but when I close the tool, the asking save filters window still show up. can you have a try?


________________________________
发件人: David Anson <notifications@github.com>
发送时间: 2017年1月16日 1:24
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Closed #39<https://github.com/TextAnalysisTool/Releases/issues/39>.

―

**Comment by daoweil** [comment]
I am using the latest version.

________________________________
发件人: Lin Daowei <daoweil@live.com>
发送时间: 2017年1月18日 3:08
收件人: TextAnalysisTool/Releases
主题: 答复: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Hi,


I try to mask some filters to dirty, but when I close the tool, the asking save filters window still show up. can you have a try?


________________________________
发件人: David Anson <notifications@github.com>
发送时间: 2017年1月16日 1:24
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Closed #39<https://github.com/TextAnalysisTool/Releases/issues/39>.

―

**Comment by vincec-msft** [comment]
Did you change the "Mark Filters Changed" setting under Edit/Preferences?

**Comment by daoweil** [comment]
yes. I try to change it to never and click apply, but when I close the APPs, the 'save' on exit still happen, and the setting was reverted to 'Always' again.

________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2017年1月18日 4:41
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Did you change the "Mark Filters Changed" setting under Edit/Preferences?

―

**Comment by vincec-msft** [comment]
Very strange. I cannot reproduce this problem so please send me the *exact* steps you are using. Also, export your preferences (Edit / Preferences / More / Export) and send the xml file.

**Comment by daoweil** [comment]
steps are very simple, like belowing:


1. open the tool, and set the 'mask filter changed' to 'never', click 'apply' and 'ok'

2. close the tool and open it again

3. check the 'mask filter changed' still keep in 'Always'


when I try to export the setting, blow window show up, but actually I already click the apply. Also I cannot see any xml configuraiton file in the program directory after install the tool.

My friends also confront the same issue.


[cid:2a48f6a4-052b-49be-86ae-2facf242715e]

[cid:f3b2864f-e948-4afe-8d78-d5efa22d5b90]



________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2017年1月19日 7:27
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Very strange. I cannot reproduce this problem so please send me the exact steps you are using. Also, export your preferences (Edit / Preferences / More / Export) and send the xml file.

―

**Comment by vincec-msft** [comment]
Is "Mark Filters Changed" the only setting that reverts to its default when the app is closed? Do the other settings work as expected?

Are you saying that you cannot export the settings at all? If you click Yes on the "Do you wish to apply the settings..." dialog you should get another dialog to specify the file name to export to. That file won't exist until you've specified the location and name.

**Comment by daoweil** [comment]
Is "Mark Filters Changed" the only setting that reverts to its default when the app is closed?


I try the other settings, it reverts to its default as well.


is there any file to save the preference(not export the setting)generally? where the preference will be saved after I change the setting? I doubt the preference was not saved properly.

________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2017年1月19日 17:27
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Is "Mark Filters Changed" the only setting that reverts to its default when the app is closed? Do the other settings work as expected?

Are you saying that you cannot export the settings at all? If you click Yes on the "Do you wish to apply the settings..." dialog you should get another dialog to specify the file name to export to. That file won't exist until you've specified the location and name.

―

**Comment by vincec-msft** [comment]
Preferences are saved in the registry under HKEY_CURRENT_USER\SOFTWARE\DavidAns\TextAnalysisTool.NET. Do you see that key? Do you have permission to write to that key?

**Comment by daoweil** [comment]
yeah, I am seeing this. but looks like some items of preferences are missed. let me check if I delete it and have a try again.


[cid:e1234a7d-b72f-4cf6-a355-d82030d774ed]


________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2017年1月20日 1:57
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Preferences are saved in the registry under HKEY_CURRENT_USER\SOFTWARE\DavidAns\TextAnalysisTool.NET. Do you see that key? Do you have permission to write to that key?

―

**Comment by daoweil** [comment]
no help, I run it as adimin by the way.


________________________________
发件人: Lin Daowei <daoweil@live.com>
发送时间: 2017年1月20日 3:31
收件人: TextAnalysisTool/Releases
主题: 答复: [TextAnalysisTool/Releases] pop save filters window very time (#39)


yeah, I am seeing this. but looks like some items of preferences are missed. let me check if I delete it and have a try again.


[cid:e1234a7d-b72f-4cf6-a355-d82030d774ed]


________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2017年1月20日 1:57
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Preferences are saved in the registry under HKEY_CURRENT_USER\SOFTWARE\DavidAns\TextAnalysisTool.NET. Do you see that key? Do you have permission to write to that key?

―

**Comment by vincec-msft** [comment]
Very interesting... a couple more questions...
Do all settings revert to their default values? Or just some?
The first setting we write is WindowState. Does that get persisted?
If you change the filter list location does the FilterListLocation setting get written to the registry?
What about the list of recent files (RecentFile0, RecentFile1, etc.)?
Did the previous version of TextAnalysisTool.NET persist settings correctly?
I'm thinking that there is a new setting that is throwing an exception when we're trying to write it and everything after that is not written. Probably the font family.

**Comment by daoweil** [comment]
All the setting will be reverted.


I check the old version (2016-06-16), preference can be saved in registry.

________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2017年1月20日 3:46
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Very interesting... a couple more questions...
Do all settings revert to their default values? Or just some?
The first setting we write is WindowState. Does that get persisted?
If you change the filter list location does the FilterListLocation setting get written to the registry?
What about the list of recent files (RecentFile0, RecentFile1, etc.)?
Did the previous version of TextAnalysisTool.NET persist settings correctly?
I'm thinking that there is a new setting that is throwing an exception when we're trying to write it and everything after that is not written. Probably the font family.

―

**Comment by daoweil** [comment]
I try to delete the registry folder name of DavidAns, and change the prefrences setting and apply it,  looks like the folder will be created again, but no registery will be created.


[cid:59706ee1-2022-48a4-a49c-994d99577524]


[cid:fee00706-fbcc-47b2-9877-54abfb326ee3]

________________________________
发件人: Lin Daowei <daoweil@live.com>
发送时间: 2017年1月20日 5:28
收件人: TextAnalysisTool/Releases
主题: 答复: [TextAnalysisTool/Releases] pop save filters window very time (#39)


All the setting will be reverted.


I check the old version (2016-06-16), preference can be saved in registry.

________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2017年1月20日 3:46
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Very interesting... a couple more questions...
Do all settings revert to their default values? Or just some?
The first setting we write is WindowState. Does that get persisted?
If you change the filter list location does the FilterListLocation setting get written to the registry?
What about the list of recent files (RecentFile0, RecentFile1, etc.)?
Did the previous version of TextAnalysisTool.NET persist settings correctly?
I'm thinking that there is a new setting that is throwing an exception when we're trying to write it and everything after that is not written. Probably the font family.

―

**Comment by vincec-msft** [comment]
Can you see this branch: https://github.com/TextAnalysisTool/Releases/tree/vincec-msft-savesettings
If so, grab the for_daoweil.zip file and run the TextAnalysisTool.NET in it.
If an exception is hit during settings save (when the app is closing) you will see a messagebox with the exception info. Please post that.
ALSO, when that message box is up please take a dump of the process and send that to me (vincec@microsoft.com). The easiest way to take the dump is in Task Manager: right click on the TextAnalysisTool.NET process and select "Create dump file."

**Comment by vincec-msft** [comment]
Okay, I can reproduce a problem with saving settings. I had to install Simplified Chinese Windows but it was worth it. :) I've filed issue #41. I'll work on a fix.

**Comment by daoweil** [comment]
Great! thanks.

________________________________
发件人: vincec-msft <notifications@github.com>
发送时间: 2017年1月21日 5:15
收件人: TextAnalysisTool/Releases
抄送: daoweil; Author
主题: Re: [TextAnalysisTool/Releases] pop save filters window very time (#39)


Okay, I can reproduce a problem with saving settings. I had to install Simplified Chinese Windows but it was worth it. :) I've filed issue #41<https://github.com/TextAnalysisTool/Releases/issues/41>. I'll work on a fix.

―
